version: "3.8"

services:

  front1:
    build: ./frontend
    depends_on:
      - back
    ports:
      - "3000:3000"
    networks:
      - reseauApp

  front2:
    build: ./frontend
    depends_on:
      - back
    ports:
      - "3002:3000"
    networks:
      - reseauApp

  back:
    build: ./backend
    depends_on:
      - database
    ports:
      - "3001:3001"
    networks: 
     - reseauApp
  
  database:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/db
    ports:
      - 27018:27017
    networks: 
     - reseauApp

  loadbalancer:
    build: ./nginx
    ports:
      - "80:80"
    networks: 
     - reseauApp
    depends_on:
      - back
      - front1
      - front2

networks:
  reseauApp:

volumes: 
  mongodb:
